name: drive_for_me_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.3
  provider: ^5.0.0
  device_preview: ^0.7.4
  carousel_pro_nullsafety:
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^2.1.0
  flutter_svg:
  easy_dynamic_theme: ^2.2.0
  firebase_core: ^1.6.0
  firebase_database: ^7.2.1
  firebase_storage: ^10.0.3
  cloud_firestore: ^2.5.1
  firebase_auth: ^3.1.0
  firebase_messaging: ^10.0.6
  google_sign_in: ^5.1.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.7
  persistent_bottom_nav_bar: ^4.0.2
  flutter_rating_bar: ^4.0.0
  http: ^0.13.3
  flutter_spinkit: ^5.1.0
  google_maps_flutter: ^2.0.8
  geolocator: ^7.6.0
  flutter_polyline_points: ^1.0.0
  background_locator: ^1.6.6
  location_permissions: ^3.0.0+1
  flutter_local_notifications:
  maps_toolkit: ^2.0.0
  url_launcher: ^6.0.10
  intl: ^0.17.0
  image_picker: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/LICENSE.txt
    - assets/fonts/Roboto-Black.ttf
    - assets/fonts/Roboto-BlackItalic.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-BoldItalic.ttf
    - assets/fonts/Roboto-Italic.ttf
    - assets/fonts/Roboto-Light.ttf
    - assets/fonts/Roboto-LightItalic.ttf
    - assets/fonts/Roboto-Medium.ttf
    - assets/fonts/Roboto-MediumItalic.ttf
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Thin.ttf
    - assets/fonts/Roboto-ThinItalic.ttf
    - assets/images/car.svg
    - assets/images/destination_map_marker.png
    - assets/images/driving_pin.png
    - assets/images/email.svg
    - assets/images/eye.svg
    - assets/images/facebook.svg
    - assets/images/google.svg
    - assets/images/google_icon.svg
    - assets/images/Google_Logo.svg.svg
    - assets/images/hide_eye.svg
    - assets/images/home.svg
    - assets/images/location.svg
    - assets/images/lock.svg
    - assets/images/logo_dark.png
    - assets/images/logo_light.png
    - assets/images/man.svg
    - assets/images/man_photo.png
    - assets/images/phone.svg
    - assets/images/phone_call.svg
    - assets/images/pick_image.svg
    - assets/images/send.svg
    - assets/images/star.svg
    - assets/images/success_circle.svg
    - assets/images/uber.png
    - assets/images/uber_x.png
    - assets/images/uber_xl.png
    - assets/images/user_man.png
    - assets/images/work_bag.svg
    - assets/maps/map_dark.txt
    - assets/maps/map_silver.txt
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
